version: '3.7'

networks:
  app-net:
    name: numbers-prod
services:
  numbers-api:
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.5"
          memory: 75M
    healthcheck:
      interval: 5s
      retries: 2
      start_period: 5s
      timeout: 3s
    image: diamol/ch08-numbers-api:v2
    networks:
      app-net: {}
  numbers-web:
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.75"
          memory: 150M
    environment:
      RngApi__Url: http://numbers-api/rng
    image: diamol/ch08-numbers-web:v2
    networks:
      app-net: {}
    ports:
    - mode: host
      published: 80
      target: 80




